// Copies the brand elements this UI uses from the suveryn-brand repository, at a pinned commit, and
// generates src/styles/tokens.css from its tokens.json. The copies are committed, so building the UI
// never needs the internet (an appliance may have no outside connection). src/brand/brand-lock.json
// records the commit and a hash of every file; a unit test fails if a file is edited by hand.
//
//   npm run brand:sync              re-sync at the commit in brand-lock.json
//   npm run brand:sync -- <commit>  move to another commit (a tag or branch name is resolved to its commit)
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const REPO = "https://github.com/suveryn/suveryn-brand.git";
const LOCK = "src/brand/brand-lock.json";
const CACHE = "node_modules/.cache/suveryn-brand";

// brand repo path -> path in this package. The mark is not AGPL (see src/brand/README.md); the
// fonts are SIL Open Font Licence and live apart from it, in src/fonts.
const FILES = {
  "logo/suveryn-icon.svg": "src/brand/suveryn-icon.svg",
  "logo/favicon.svg": "public/favicon.svg",
  "logo/apple-touch-icon.png": "public/apple-touch-icon.png",
  "fonts/Inter/Inter-Variable.woff2": "src/fonts/Inter/Inter-Variable.woff2",
  "fonts/Inter/OFL.txt": "src/fonts/Inter/OFL.txt",
  "fonts/SpaceGrotesk/SpaceGrotesk-Variable.woff2": "src/fonts/SpaceGrotesk/SpaceGrotesk-Variable.woff2",
  "fonts/SpaceGrotesk/OFL.txt": "src/fonts/SpaceGrotesk/OFL.txt",
  "fonts/IBMPlexMono/IBMPlexMono-Medium.woff2": "src/fonts/IBMPlexMono/IBMPlexMono-Medium.woff2",
  "fonts/IBMPlexMono/OFL.txt": "src/fonts/IBMPlexMono/OFL.txt",
};
const TOKENS_CSS = "src/styles/tokens.css";

const git = (...args) => execFileSync("git", ["-C", CACHE, ...args], { encoding: "utf8" }).trim();
const sha256 = (path) => createHash("sha256").update(readFileSync(path)).digest("hex");

const wanted = process.argv[2] ?? JSON.parse(readFileSync(LOCK, "utf8")).commit;
// A commit, tag or branch name only: anything starting with "-" would be read by git as an option.
if (!/^[\w][\w./-]*$/.test(wanted)) throw new Error(`not a commit, tag or branch name: ${wanted}`);
rmSync(CACHE, { recursive: true, force: true });
mkdirSync(CACHE, { recursive: true });
git("init", "-q");
git("fetch", "-q", "--depth", "1", REPO, wanted);
git("checkout", "-q", "FETCH_HEAD");
const commit = git("rev-parse", "HEAD");

for (const [from, to] of Object.entries(FILES)) {
  mkdirSync(dirname(to), { recursive: true });
  copyFileSync(`${CACHE}/${from}`, to);
}
writeFileSync(TOKENS_CSS, tokensCss(JSON.parse(readFileSync(`${CACHE}/tokens/tokens.json`, "utf8")), commit));

const files = Object.fromEntries([...Object.values(FILES), TOKENS_CSS].sort().map((p) => [p, sha256(p)]));
writeFileSync(LOCK, JSON.stringify({ source: REPO, commit, files }, null, 2) + "\n");
rmSync(CACHE, { recursive: true, force: true });
console.log(`brand: ${Object.keys(files).length} files from suveryn-brand@${commit.slice(0, 7)}`);

/** The light theme as CSS custom properties: colours, font families, spacing and radius. */
function tokensCss(t, commit) {
  const colour = (v) => (typeof v === "object" ? v.light : v).replace(/^\{(.+)\}$/, "var(--$1)");
  const lines = [
    "/*",
    ` * GENERATED by scripts/brand-sync.mjs from suveryn-brand@${commit.slice(0, 7)} tokens/tokens.json. Do not edit:`,
    " * change the brand repository and re-sync. Light theme (the product UI).",
    " * Contrast rule: text and icons on `accent` (or teal) always use `on-accent`, never white.",
    " */",
    ":root {",
    "  color-scheme: light;",
    "",
    "  /* colour */",
    ...t.color.tokens.map((c) => `  --${c.name}: ${colour(c.value)};`),
    "",
    "  /* type */",
    ...Object.entries(t.type.families).map(([k, v]) => `  --font-${k}: ${v};`),
    "",
    "  /* spacing */",
    ...t.spacing.tokens.map((s) => `  --${s.name}: ${s.value};`),
    "",
    "  /* radius */",
    ...t.radius.tokens.map((r) => `  --${r.name}: ${r.value};`),
    "}",
    "",
  ];
  return lines.join("\n");
}
